### ISSUE TITLE
Docker build error: package devtools is not available

### ISSUE THREAD

**Issue by abreschi** [guigolab/ggsashimi#45] opened 2020-09-24 04:58 UTC
Hi! I was trying to run it via docker and started building the image:
`docker build -f docker/Dockerfile -t guigolab/ggsashimi .`

However it complains about devtools:
```
Step 6/14 : RUN R -e 'install.packages("devtools");' &&     R -e "require(devtools); install_version('ggplot2', version = '${GGPLOT_VER}', repos = 'http://cloud.r-project.org');"
 ---> Running in fcc8a5f682b6

R version 3.3.3 (2017-03-06) -- "Another Canoe"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages("devtools");
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://mran.microsoft.com/snapshot/2017-04-21/src/contrib:
  Line starting '<!doctype html><html ...' is malformed!
Warning message:
package ‘devtools’ is not available (for R version 3.3.3)
>
>

R version 3.3.3 (2017-03-06) -- "Another Canoe"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> require(devtools); install_version('ggplot2', version = '2.2.1', repos = 'http://cloud.r-project.org');
Loading required package: devtools
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘devtools’
Error: could not find function "install_version"
Execution halted
The command '/bin/sh -c R -e 'install.packages("devtools");' &&     R -e "require(devtools); install_version('ggplot2', version = '${GGPLOT_VER}', repos = 'http://cloud.r-project.org');"' returned a non-zero code: 1
```

thoughts?

**Comment by dgarrimar** [comment] 2020-09-30 08:42
We will check that, and add it to the CI too

**Comment by abreschi** [comment] 2020-11-16 23:19
Hello! Did you have a chance to check this issue? Has anyone else had the same error?

**Comment by emi80** [comment] 2021-01-21 13:57
Hello @abreschi. Apologies for the late feedback. I have just tried to run the same command and I could build the image successfully. 
Can you please try again and let me know if you still have this issue?

**Comment by dgarrimar** [comment] 2021-01-21 19:20
I also tried, and works fine for me too (even in [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux)!)

**Comment by emi80** [comment] 2021-01-27 11:40
I understand this was the specific issue:

```
Warning: unable to access index for repository https://mran.microsoft.com/snapshot/2017-04-21/src/contrib:
  Line starting '<!doctype html><html ...' is malformed!
```

This looks like a network issue or an external error from the mirror which might have been fixed in the meantime.

**Comment by emi80** [comment] 2021-02-04 10:59
I close this as it's not reproducible. @abreschi feel free to reopen it if you get this issue again and we can reproduce it.

**Closed by emi80** 2021-02-04 10:59 UTC
